# Generated by Django 6.0.3 on 2026-04-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('tree_count', models.PositiveIntegerField()),
                ('problem', models.TextField()),
                ('address', models.TextField()),
                ('time_slot', models.CharField(choices=[('08:30-09:30', '08:30 - 09:30'), ('10:00-11:00', '10:00 - 11:00'), ('15:00-16:00', '15:00 - 16:00'), ('16:30-17:30', '16:30 - 17:30'), ('18:00-19:00', '18:00 - 19:00')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('client_confirmed', 'Client Confirmed'), ('client_rejected', 'Client Rejected')], db_index=True, default='pending', max_length=20)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agronomist', models.ForeignKey(limit_choices_to={'role': 'agronomist'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='accounts.telegramuser')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='accounts.telegramuser')),
                ('sales_manager', models.ForeignKey(limit_choices_to={'role': 'sales_manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='accounts.telegramuser')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='TreatmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_count', models.PositiveIntegerField()),
                ('root_treatment_applied', models.BooleanField(default=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20)),
                ('re_treatment_needed', models.BooleanField(default=False)),
                ('re_treatment_date', models.DateField(blank=True, null=True)),
                ('re_treatment_notified', models.BooleanField(default=False)),
                ('proof_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_file_type', models.CharField(blank=True, choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Treatment Details',
                'verbose_name_plural': 'Treatment Details',
                'db_table': 'treatment_details',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['agronomist', 'status'], name='orders_agronom_96bf78_idx'),
        ),
    ]
