# Generated by Django 6.0.3 on 2026-04-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyinfo_faqitem_telegramuser_language_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('sales_created', 'Sales Created'), ('client_created', 'Client Created')], default='sales_created', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='agronomist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agronomist'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to='accounts.telegramuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sales_manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='accounts.telegramuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_sales', 'Awaiting Sales'), ('awaiting_client', 'Awaiting Client'), ('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('client_confirmed', 'Client Confirmed'), ('client_rejected', 'Client Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('08:30-09:30', '08:30 - 09:30'), ('10:00-11:00', '10:00 - 11:00'), ('15:00-16:00', '15:00 - 16:00'), ('16:30-17:30', '16:30 - 17:30'), ('18:00-19:00', '18:00 - 19:00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tree_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
    ]
