# Generated by Django 6.0.3 on 2026-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_source_alter_order_agronomist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
