# Generated by Django 6.0.3 on 2026-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+998 XX XXX XX XX', max_length=50)),
                ('address_uz', models.TextField(default="Manzil ko'rsatilmagan")),
                ('address_ru', models.TextField(default='Адрес не указан')),
                ('address_uz_kr', models.TextField(blank=True, default='Манзил кўрсатилмаган')),
                ('address_en', models.TextField(blank=True, default='Address not specified')),
                ('website', models.CharField(blank=True, max_length=255)),
                ('price_info_uz', models.TextField(blank=True, verbose_name='Narxlar (UZ)')),
                ('price_info_ru', models.TextField(blank=True, verbose_name='Цены (RU)')),
                ('price_info_uz_kr', models.TextField(blank=True, verbose_name='Нархлар (УЗ Кр)')),
                ('price_info_en', models.TextField(blank=True, verbose_name='Prices (EN)')),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.TextField(verbose_name='Savol (UZ)')),
                ('question_ru', models.TextField(verbose_name='Вопрос (RU)')),
                ('question_uz_kr', models.TextField(blank=True, verbose_name='Савол (УЗ Кр)')),
                ('question_en', models.TextField(blank=True, verbose_name='Question (EN)')),
                ('answer_uz', models.TextField(verbose_name='Javob (UZ)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (RU)')),
                ('answer_uz_kr', models.TextField(blank=True, verbose_name='Жавоб (УЗ Кр)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'db_table': 'faq_items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('uz_kr', 'Ўзбек'), ('en', 'English')], default='uz', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='registered_via',
            field=models.CharField(choices=[('client_bot', 'Client Bot'), ('main_bot', 'Main Bot'), ('admin', 'Admin Panel')], default='admin', max_length=20),
        ),
    ]
